# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install uv which is required to run the MCP server as indicated in the README
RUN pip install uv fastmcp requests

# Copy the project files
WORKDIR /app
COPY . /app

# Expose any necessary ports (if needed), though MCP typically uses stdio

CMD ["uv", "run", "--with", "fastmcp", "--with", "requests", "fastmcp", "run", "server.py"]
